- dataSource: lambdaDatasource
  type: Query
  field: getUser
  request: getUser-request-mapping-template.vtl
  response: common-response-mapping-template.vtl

- dataSource: lambdaDatasource
  type: Query
  field: allUsers
  request: allUsers-request-mapping-template.vtl
  response: common-response-mapping-template.vtl
  
- dataSource: lambdaDatasource
  type: Query
  field: getStores
  request: getStores-request-mapping-template.vtl
  response: common-response-mapping-template.vtl

- dataSource: lambdaDatasource
  type: Mutation
  field: deleteUser
  request: deleteUser-request-mapping-template.vtl
  response: common-response-mapping-template.vtl

- dataSource: lambdaDatasource
  type: Mutation
  field: createStore
  request: createStore-request-mapping-template.vtl
  response: common-response-mapping-template.vtl

- dataSource: lambdaDatasource
  type: Mutation
  field: createUser
  request: createUser-request-mapping-template.vtl
  response: common-response-mapping-template.vtl